#!/bin/zsh

function get_brainyquote(){
  rssdata="$(curl -s https://www.brainyquote.com/link/quotefu.rss -o-)"
  author="$(echo $rssdata | xmlstarlet sel -T -t -v /rss/channel/item/title 2> /dev/null | head -1)"
  desc=$(echo $rssdata | xmlstarlet sel -T -t -v /rss/channel/item/description 2> /dev/null | head -1 | sed -E "s/\"(.*)\"/\1/g")
  text="$desc""\n""$author"
  echo $text
}

function get_nointernet(){
  echo "On the Internet, nobody knows you are a dog.\nAnonymous"
}

function get_quotesday() {
  text=$(elinks https://www.quotes-day.com/ -dump -no-references -no-numbering |\
  grep "Funny Quote of the Day" -A 10 | grep "Love" -B 10 |\
  tail +3 | head --lines=-1 |\
  sed -E "s/[[:space:]]{2,}//g" | tr "\n" " " | tr "-" "\n")
  echo $text
}

function get_quote() {
  if [[ "$(nmcli networking connectivity check)" != "none" ]] then; 
    get_brainyquote | write_tofile
  elif [[ ! -f ~/.dailyquote ]]; then
    get_nointernet | write_tofile
  fi
}

function write_tofile(){
  read text;
  echo $text | fold -w 35 -s | python ~/.scripts/tools/boxes.py > ~/.dailyquote
}

if [[ ! -f ~/.dailyquote ]] || [[ $(( $(date +%s) - $(stat -c %Y ~/.dailyquote) > 14400)) -eq 1 ]];
then
  get_quote
fi

lolcat ~/.dailyquote -F 0.2 #-p 30000
