#!/bin/zsh

if [[ ! -f ~/.dailyquote ]] || [[ $(( $(date +%s) - $(stat -c %Y ~/.dailyquote) > 14400)) -eq 1 ]] ;
then
    rssdata="$(curl -s https://www.brainyquote.com/link/quotefu.rss -o-)"
    author="$(echo $rssdata | xmlstarlet sel -T -t -v /rss/channel/item/title 2> /dev/null | head -1)"
    desc=$(echo $rssdata | xmlstarlet sel -T -t -v /rss/channel/item/description 2> /dev/null | head -1 | sed -E "s/\"(.*)\"/\1/g")
    text="$desc""\n""$author"
    echo $text | fold -w 35 -s | python ~/.scripts/tools/boxes.py > ~/.dailyquote
fi 

lolcat ~/.dailyquote -F 0.6 -p 30000 
